#!/bin/bash
# Basic aliases
alias ls="eza --color=always --git --icons=always"
alias vim="nvim"
alias vi="nvim"
alias refresh="source ~/.zshrc"
alias src="source ~/.zshrc"
alias la="lsd -a"
alias ll="lsd -l"
alias lla="lsd -la"
alias zshconf="vim ~/.zshrc"
alias pyglobalenv="source ~/venv/bin/activate"
alias sudo="sudo -E -s"
alias cl="clear;clear"
alias time="sh ~/.config/zsh/time.sh"
alias memory="sh ~/.config/zsh/memory.sh"
alias y="yazi"
alias cd="z"
alias cat="bat"

# Navigation aliases
alias desk="z ~/Desktop"
alias down="z ~/Downloads"
alias ohmyzsh="z ~/.oh-my-zsh"
alias vimconf="z ~/.config/nvim"
alias tmuxconf="z ~/.config/tmux"
alias gitconf="z ~/.config/git"
alias home="z ~"
alias proj="z ~/projects"
alias shellconf="z ~/.config/zsh"
alias wezconf="z ~/.config/wezterm"
alias yaziconf="z ~/.config/yazi"
alias credconf="z ~/.config/creds"
alias aeroconf="z ~/.config/aerospace"
alias sketchyconf="z ~/.config/sketchybar"
alias dotfiles="z ~/dotfiles"
alias config="z ~/.config"

# Git aliases
alias g="git"
alias gi="git init"
alias gs="git status"
alias ga="git add"
alias gc="git commit"
alias gcm="git commit -m"
alias gco="git checkout"
alias gcb="git checkout -b"
alias gp="git push"
alias gpl="git pull"
alias gl="git log"
alias gls="git log --show-signature"
alias gd="git diff"
alias gds="git diff --staged"

# Git Worktree aliases

alias gw="git worktree"
alias gwa="git worktree add"
alias gwl="git worktree list"
alias gwr="git worktree remove"

alias getrepo="~/.config/zsh/getrepo.sh"
