#!/bin/zsh

_MPROJ_PY_SCRIPT="$_PYTHON_DIR/mproj.py"

# This is the internal command called by the 'enigma' dispatcher.
# It's a dispatcher itself, handling special cases like 'add' and 'launch'.
function _mproj_cmd() {
    local command="$1"
    
    case "$command" in
        add)
            local proj_name="$2"
            if [[ -z "$proj_name" ]]; then
                # Use our python script's styled error handler
                "$_PYTHON_VENV_EXECUTABLE" "$_MPROJ_PY_SCRIPT" add
                return 1
            fi

            # Use fd and fzf to select a directory
            local selected_path
            selected_path=$(fd --type d --max-depth 3 . "$HOME/projects" 2>/dev/null | fzf --height 40% --reverse --prompt="Select directory for '$proj_name'> ")
            
            # If a path was selected (not cancelled)
            if [[ -n "$selected_path" ]]; then
                # Call the python script with the name and selected path
                "$_PYTHON_VENV_EXECUTABLE" "$_MPROJ_PY_SCRIPT" add "$proj_name" --path "$selected_path"
            fi
            ;;
        
        launch)
            # Use the robust temp-file pattern to avoid deadlocks
            local tmpfile
            tmpfile=$(mktemp) || return 1
            
            "$_PYTHON_VENV_EXECUTABLE" "$_MPROJ_PY_SCRIPT" --outfile "$tmpfile" launch
            local exit_code=$?
            
            if [[ $exit_code -eq 0 && -s "$tmpfile" ]]; then
                # Source the script generated by python
                source "$tmpfile"
            fi
            rm -f "$tmpfile"
            ;;
            
        *)
            # For all other commands (ls, edit, rm, mv, help), just pass through
            "$_PYTHON_VENV_EXECUTABLE" "$_MPROJ_PY_SCRIPT" "$@"
            ;;
    esac
}
