# --- Application Shortcuts ---
$downloads = nautilus ~/Downloads
$weztermWallpapers = nautilus ~/wezterm-wallpapers
$backgrounds = nautilus ~/.config/backgrounds
$home = nautilus ~
$config = nautilus ~/.config
$menu = rofi -show drun -show-icons -display-drun "Apps" -theme ~/.config/rofi/launcher-elegant.rasi

# --- Application Shortcuts ($mainMod + ALT) ---
bind = $mainMod ALT, B, exec, brave --enable-features=UseOzonePlatform --ozone-platform=x11
bind = $mainMod ALT, S, exec, spotify
bind = $mainMod ALT, D, exec, $downloads
bind = $mainMod ALT, G, exec, $backgrounds
bind = $mainMod ALT, C, exec, $config
bind = $mainMod ALT, H, exec, $home


# --- Other App-related Shortcuts ---
bind = $mainMod, RETURN, exec, ~/.config/hypr/scripts/launch_kitty.sh
bind = $mainMod, SPACE, exec, $menu
bind = $mainMod CTRL, V, exec, ~/.config/hypr/scripts/clipboard.sh
bind = $mainMod CTRL, B, exec, ~/.config/waybar/scripts/launch_bluetooth.sh
bind = $mainMod CTRL, N, exec, ~/.config/waybar/scripts/swaync-client.sh
