# --- Application Shortcuts ---
$downloads = nautilus ~/Downloads
$weztermWallpapers = nautilus ~/wezterm-wallpapers
$backgrounds = nautilus ~/.config/backgrounds
$home = nautilus ~
$config = nautilus ~/.config
$menu = walker --height 800 --width 1200 --placeholder "Search for applications"

bind = $mainMod, RETURN, exec, ~/.config/hypr/scripts/launch_kitty.sh
bind = $mainMod, SPACE, exec, $menu
bind = $mainMod SHIFT, C, exec, $config
# bind = SUPER_SHIFT, W, exec, $weztermWallpapers
bind = $mainMod SHIFT, B, exec, $backgrounds
bind = $mainMod SHIFT, D, exec, $downloads
bind = $mainMod SHIFT, HOME, exec, $home
bind = $mainMod, B, exec, brave --enable-features=UseOzonePlatform --ozone-platform=x11
bind = $mainMod, S, exec, spotify
bind = $mainMod CTRL, V, exec, ~/.config/hypr/scripts/clipboard.sh
