# --- Hardware Keys & System Utilities ---
binde = , XF86AudioRaiseVolume, exec, ~/.config/waybar/scripts/volume-control.sh up
binde = , XF86AudioLowerVolume, exec, ~/.config/waybar/scripts/volume-control.sh down
bind = , XF86AudioMute, exec, pactl set-sink-mute @DEFAULT_SINK@ toggle

bind = , XF86MonBrightnessUp, exec, brightnessctl set +5%
bind = , XF86MonBrightnessDown, exec, brightnessctl set 5%-

bind = , Print, exec, ~/.config/hypr/scripts/screenshot_edit.sh
bind = SHIFT, Print, exec, ~/.config/hypr/scripts/screenshot_edit.sh