# --- Hardware Keys & System Utilities ---
binde = , XF86AudioRaiseVolume, exec, ~/.config/waybar/scripts/volume-control.sh up
binde = , XF86AudioLowerVolume, exec, ~/.config/waybar/scripts/volume-control.sh down
bind = , XF86AudioMute, exec, pactl set-sink-mute @DEFAULT_SINK@ toggle
bind = , XF86AudioPlay, exec, playerctl play-pause
bind = , XF86AudioNext, exec, playerctl next
bind = , XF86AudioPrev, exec, playerctl previous

bind = , XF86MonBrightnessUp, exec, brightnessctl set +5%
bind = , XF86MonBrightnessDown, exec, brightnessctl set 5%-

bind = , Print, exec, ~/.config/hypr/scripts/screenshot_screen_edit.sh
bind = SUPER, Print, exec, ~/.config/hypr/scripts/screenshot_window_edit.sh
bind = SUPER SHIFT, Print, exec, ~/.config/hypr/scripts/screenshot_edit.sh
