# --- Hyprland System Controls ---
bind = $mainMod CTRL, M, exit,          # Exit Hyprland session
bind = $mainMod CTRL, R, exec, hyprctl reload && notify-send -i "dialog-information" -a "Hyprland" "Hyprland" "Config reloaded successfully!" # Reload Hyprland config
bind = $mainMod CTRL, L, exec, hyprlock      # Lock the screen
bind = $mainMod CTRL, S, exec, systemctl suspend # Suspend the system
bind = $mainMod CTRL, H, exec, ~/.config/hypr/scripts/toggle_hypridle.sh # Toggle hypridle

bind = $mainMod CTRL, X, exec, ~/.config/waybar/scripts/power-menu.sh

bind = $mainMod CTRL, W, exec, ~/.config/hypr/scripts/set_wallpaper.sh

# Monitor Profile Manager (Ctrl+Super+D)
bind = $mainMod CTRL, D, exec, ~/.config/hypr/scripts/monitor_profile_manager.sh menu
bind = $mainMod CTRL SHIFT, D, exec, ~/.config/hypr/scripts/monitor_profile_manager.sh auto
