# -----------------------------------------------------------------------------
# Cisco apps (AnyConnect, Secure Client, etc.)
# -----------------------------------------------------------------------------

windowrule = float on, match:class (?i).*cisco.*
windowrule = workspace special:Ad-Hoc, match:class (?i).*cisco.*
