# -----------------------------------------------------------------------------
# JetBrains windows default size
# -----------------------------------------------------------------------------

windowrule = size 50% 50%, match:class (.*jetbrains.*)$, match:title ^$


# -----------------------------------------------------------------------------
# Fix tab dragging (tab titles are just one space)
# -----------------------------------------------------------------------------

windowrule = no_initial_focus on, match:class ^(.*jetbrains.*)$, match:title ^\s$


# -----------------------------------------------------------------------------
# Allow dialogs (e.g. "Send usage statistics") to be focusable & clickable
# -----------------------------------------------------------------------------

# Unset nofocus/noinitialfocus for these specific windows if they matched previous rules
# Note: 'unset' is for clearing ALL group rules according to doc, OR workspace. 
# For standard effects, we just toggle them off if they were previously on? 
# Or does "unset" work for properties?
# The doc says: "You can also set [w] to unset. This will unset all previous workspace rules applied to this window."
# It does NOT explicitly say 'unset' works for 'no_focus'.
# However, usually we can just set 'no_focus off'.
windowrule = no_focus off, match:class ^(.*jetbrains.*)$, match:title ^$
windowrule = no_initial_focus off, match:class ^(.*jetbrains.*)$, match:title ^$
