# -----------------------------------------------------------------------------
# RetroArch
# -----------------------------------------------------------------------------

windowrule = fullscreen on, match:class ^com\.libretro\.RetroArch$
windowrule = opacity 1.0 override 1.0 override, match:class ^com\.libretro\.RetroArch$
windowrule = idle_inhibit fullscreen, match:class ^com\.libretro\.RetroArch$
