# -----------------------------------------------------------------------------
# Steam
# -----------------------------------------------------------------------------

# Float all Steam windows
windowrule = float on, match:class ^steam$

# Center main Steam window
windowrule = center on, match:class ^steam$, match:title ^Steam$

# Ensure Steam is always fully opaque
windowrule = opacity 1.0 override 1.0 override, match:class ^steam$

# Sizes for specific Steam windows
windowrule = size 1100 700, match:class ^steam$, match:title ^Steam$
windowrule = size 460 800, match:class ^steam$, match:title ^Friends List$

# Prevent idle / screen blanking when Steam goes fullscreen (e.g. games)
windowrule = idle_inhibit fullscreen, match:class ^steam$
