local M = {}

M.mason_tools_ensure_installed = {
	"prettier",
	"stylua",
	"isort",
	"black",
	"ruff",
	"eslint_d",
	"markdownlint",
	"luacheck",
	"jsonlint",
	"shellcheck",
	"yamllint",
}

M.lspconfig_ensure_installed = {
	"ts_ls",
	"eslint",
	"pylsp",
	"lua_ls",
	"marksman",
	"vimls",
	"bashls",
	"dockerls",
	"jsonls",
	"html",
	"yamlls",
	"cssls",
	"graphql",
}

M.yamlls_setup = {
	cmd = { "yaml-language-server", "--stdio" },
	filetypes = { "yaml", "yml", "yaml.docker-compose" },
	settings = {
		yaml = {
			schemas = {
				["https://raw.githubusercontent.com/aws/serverless-application-model/main/samtranslator/schema/schema.json"] = "sam-schema.json",
				["https://raw.githubusercontent.com/awslabs/goformation/master/schema/cloudformation.schema.json"] = "cloudformation-schema.json",
			},
			customTags = {
				"!And scalar",
				"!And sequence",
				"!And mapping",
				"!If scalar",
				"!If sequence",
				"!If mapping",
				"!Not scalar",
				"!Not sequence",
				"!Not mapping",
				"!Equals scalar",
				"!Equals sequence",
				"!Equals mapping",
				"!Or scalar",
				"!Or sequence",
				"!Or mapping",
				"!FindInMap scalar",
				"!FindInMap sequence",
				"!FindInMap mapping",
				"!Base64 scalar",
				"!Base64 sequence",
				"!Base64 mapping",
				"!Cidr scalar",
				"!Cidr sequence",
				"!Cidr mapping",
				"!Ref scalar",
				"!Ref sequence",
				"!Ref mapping",
				"!Sub scalar",
				"!Sub sequence",
				"!Sub mapping",
				"!GetAtt scalar",
				"!GetAtt sequence",
				"!GetAtt mapping",
				"!GetAZs scalar",
				"!GetAZs sequence",
				"!GetAZs mapping",
				"!ImportValue scalar",
				"!ImportValue sequence",
				"!ImportValue mapping",
				"!Select scalar",
				"!Select sequence",
				"!Select mapping",
				"!Split scalar",
				"!Split sequence",
				"!Split mapping",
				"!Join scalar",
				"!Join sequence",
				"!Join mapping",
				"!ImportValue scalar",
				"!ImportValue sequence",
				"!ImportValue mapping",
				"!Select scalar",
				"!Select sequence",
				"!Select mapping",
				"!Split scalar",
				"!Split sequence",
				"!Split mapping",
				"!Join scalar",
				"!Join sequence",
				"!Join mapping",
				"!ImportValue scalar",
				"!ImportValue sequence",
				"!ImportValue mapping",
				"!Select scalar",
				"!Select sequence",
				"!Select mapping",
				"!Split scalar",
				"!Split sequence",
				"!Split mapping",
				"!Join scalar",
				"!Join sequence",
				"!Join mapping",
				"!ImportValue scalar",
				"!ImportValue sequence",
				"!ImportValue mapping",
				"!Select scalar",
				"!Select sequence",
				"!Select mapping",
				"!Split scalar",
				"!Split sequence",
				"!Split mapping",
				"!Join scalar",
				"!Join sequence",
				"!Join mapping",
				"!ImportValue scalar",
				"!ImportValue sequence",
				"!ImportValue mapping",
				"!Select scalar",
				"!Select sequence",
				"!Select mapping",
				"!Split scalar",
				"!Split sequence",
			},
		},
	},
}

M.pylsp_setup = {
	settings = {
		pylsp = {
			plugins = {
				-- formatter options
				black = { enabled = true },
				autopep8 = { enabled = true },
				yapf = { enabled = false },
				-- linter options
				-- pylint = { enabled = true, executable = "pylint" },
				pyflakes = { enabled = false },
				pycodestyle = {
					enabled = true,
					ignore = { "W391" },
					maxLineLength = 120,
				},
				-- type checker
				pylsp_mypy = { enabled = true },
				-- auto-completion options
				jedi_completion = { fuzzy = true },
				-- import sorting
				pyls_isort = { enabled = true },
			},
		},
	},
}

return M
