-- luacheck: globals vim
local M = {}
local capabilities = require("cmp_nvim_lsp").default_capabilities()

M.mason_tools_ensure_installed = {
	"prettier",
	"stylua",
	"isort",
	"black",
	"ruff",
	"eslint_d",
	"markdownlint",
	"luacheck",
	"jsonlint",
	"shellcheck",
	"yamllint",
	"pyproject-fmt",
}

M.lspconfig_ensure_installed = {
	"ts_ls",
	"eslint",
	"pylsp",
	"lua_ls",
	"marksman",
	"vimls",
	"bashls",
	"dockerls",
	"jsonls",
	"html",
	"yamlls",
	"cssls",
	"graphql",
	"taplo",
}

M.lua_opts = {
	capabilities = capabilities,
	settings = {
		Lua = {
			diagnostics = { globals = { "vim" } },
			workspace = {
				library = vim.api.nvim_get_runtime_file("", true),
				checkThirdParty = false,
			},
		},
	},
}

M.yamlls_setup = {
	cmd = { "yaml-language-server", "--stdio" },
	filetypes = { "yaml", "yml", "yaml.docker-compose" },
	settings = {
		yaml = {
			schemas = {
				["https://raw.githubusercontent.com/aws/serverless-application-model/main/samtranslator/schema/schema.json"] = "sam-schema.json",
				["https://raw.githubusercontent.com/awslabs/goformation/master/schema/cloudformation.schema.json"] = "cloudformation-schema.json",
			},
			customTags = {
				"!And scalar",
				"!And sequence",
				"!And mapping",
				"!If scalar",
				"!If sequence",
				"!If mapping",
				"!Not scalar",
				"!Not sequence",
				"!Not mapping",
				"!Equals scalar",
				"!Equals sequence",
				"!Equals mapping",
				"!Or scalar",
				"!Or sequence",
				"!Or mapping",
				"!FindInMap scalar",
				"!FindInMap sequence",
				"!FindInMap mapping",
				"!Base64 scalar",
				"!Base64 sequence",
				"!Base64 mapping",
				"!Cidr scalar",
				"!Cidr sequence",
				"!Cidr mapping",
				"!Ref scalar",
				"!Ref sequence",
				"!Ref mapping",
				"!Sub scalar",
				"!Sub sequence",
				"!Sub mapping",
				"!GetAtt scalar",
				"!GetAtt sequence",
				"!GetAtt mapping",
				"!GetAZs scalar",
				"!GetAZs sequence",
				"!GetAZs mapping",
				"!ImportValue scalar",
				"!ImportValue sequence",
				"!ImportValue mapping",
				"!Select scalar",
				"!Select sequence",
				"!Select mapping",
				"!Split scalar",
				"!Split sequence",
				"!Split mapping",
				"!Join scalar",
				"!Join sequence",
				"!Join mapping",
				"!ImportValue scalar",
				"!ImportValue sequence",
				"!ImportValue mapping",
				"!Select scalar",
				"!Select sequence",
				"!Select mapping",
				"!Split scalar",
				"!Split sequence",
				"!Split mapping",
				"!Join scalar",
				"!Join sequence",
				"!Join mapping",
				"!ImportValue scalar",
				"!ImportValue sequence",
				"!ImportValue mapping",
				"!Select scalar",
				"!Select sequence",
				"!Select mapping",
				"!Split scalar",
				"!Split sequence",
				"!Split mapping",
				"!Join scalar",
				"!Join sequence",
				"!Join mapping",
				"!ImportValue scalar",
				"!ImportValue sequence",
				"!ImportValue mapping",
				"!Select scalar",
				"!Select sequence",
				"!Select mapping",
				"!Split scalar",
				"!Split sequence",
				"!Split mapping",
				"!Join scalar",
				"!Join sequence",
				"!Join mapping",
				"!ImportValue scalar",
				"!ImportValue sequence",
				"!ImportValue mapping",
				"!Select scalar",
				"!Select sequence",
				"!Select mapping",
				"!Split scalar",
				"!Split sequence",
			},
		},
	},
}

M.pylsp_setup = {
	settings = {
		pylsp = {
			plugins = {
				pyflakes = { enabled = false },
				pycodestyle = {
					enabled = false,
					ignore = { "W391" },
					maxLineLength = 120,
				},
				autopep8 = { enabled = false },
				yapf = { enabled = false },
				mccabe = { enabled = false },
				black = { enabled = false },
				pylsp_mypy = { enabled = false },
				pylsp_black = { enabled = false },
				jedi_completion = { fuzzy = true },
				pyls_isort = { enabled = false },
			},
		},
	},
}

return M
