# This provides a safe, default wallpaper so hyprpaper never crashes on startup.
# The startup script will override this with a random wallpaper a moment later.
preload = ~/.config/backgrounds/Anime-Girl1.png
wallpaper = ,~/.config/backgrounds/Anime-Girl1.png
