# --- Programs and Services to Execute at Launch ---
exec-once = waybar & swaync & hyprpaper & hypridle
exec-once = ~/.config/hypr/scripts/kanshi-wrapper.sh
exec-once = hyprctl setcursor catppuccin-mocha-dark-cursors 28
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = wl-paste --watch cliphist store
exec-once = nm-applet --indicator


exec-once = ~/.config/hypr/scripts/set_wallpaper.sh --init

