# --- Programs and Services to Execute at Launch ---
# critical for dbus/notifications
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP DBUS_SESSION_BUS_ADDRESS
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP DBUS_SESSION_BUS_ADDRESS

exec-once = waybar & swaync & hyprpaper & hypridle
exec-once = hyprctl setcursor catppuccin-mocha-dark-cursors 28
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = wl-paste --watch cliphist store
exec-once = nm-applet --indicator


exec-once = ~/.config/hypr/scripts/set_wallpaper.sh --init

# Start monitor event listener for automatic profile switching
exec-once = ~/.config/hypr/scripts/launch_monitor_listener.sh

# Start hot corners (screen corner triggers)
exec-once = ~/.config/hypr/scripts/hot_corners.sh

