# --- Main Modifier Key ---
$mainMod = SUPER

# Source all files in the bindings directory
source=~/.config/hypr/bindings/apps.conf
source=~/.config/hypr/bindings/system.conf
source=~/.config/hypr/bindings/tiling.conf
source=~/.config/hypr/bindings/workspaces.conf
source=~/.config/hypr/bindings/media.conf
source=~/.config/hypr/bindings/mouse.conf
source=~/.config/hypr/bindings/groups.conf
